/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAlerts: typeof import('./src/@core/components/AAlerts/index.vue')['default']
    AAvatars: typeof import('./src/@core/components/AAvatars/index.vue')['default']
    ABadges: typeof import('./src/@core/components/ABadges/index.vue')['default']
    AButton: typeof import('./src/@core/components/AButton/index.vue')['default']
    AList: typeof import('./src/@core/components/AList/index.vue')['default']
    AppLoadingIndicator: typeof import('./src/components/AppLoadingIndicator.vue')['default']
    ATabs: typeof import('./src/@core/components/ATabs/index.vue')['default']
    Avatars: typeof import('./src/@core/components/Avatars/index.vue')['default']
    Button: typeof import('./src/@core/components/Button.vue')['default']
    copy: typeof import('./src/@core/components/AList copy/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
